src/cached_tokenizers.rs, src/caps.rs
* vllm alias for refact model
* deepseek models support
* EOF tokenizer on start fix
=> Caps and tokenizer improvements

src/http/routers/v1/snippet_accepted.rs, src/telemetry/snippets_transmit.rs, src/telemetry/utils.rs
fixed bug in handle_v1_snippet_accepted
=> fixed issue in handle_v1_snippet_accepted; minor

src/lsp.rs
=> add exception-handling in getCompletion

src/ast/ast_index.rs, src/ast/ast_index_service.rs, src/ast/ast_module.rs, src/ast/file_splitter.rs, src/ast/structs.rs, src/ast/treesitter/ast_instance_structs.rs, src/ast/treesitter/parsers.rs, src/ast/treesitter/parsers/java.rs, src/ast/treesitter/parsers/python.rs, src/ast/treesitter/parsers/rust.rs, src/ast/usages_declarations_merger.rs, src/at_commands/at_ast_definition.rs, src/at_commands/at_ast_file_symbols.rs, src/at_commands/at_ast_lookup_symbols.rs, src/at_commands/at_ast_reference.rs, src/at_commands/at_file.rs, src/files_in_jsonl.rs, src/files_in_workspace.rs, src/global_context.rs, src/http/routers/v1/ast.rs, src/http/routers/v1/lsp_like_handlers.rs, src/lsp.rs, src/scratchpads/chat_utils_rag.rs, src/scratchpads/completion_single_file_fim.rs, src/vecdb/file_filter.rs, src/vecdb/file_splitter.rs, src/vecdb/vecdb.rs, src/vecdb/vectorizer_service.rs, tests/post_doc_info.py
Changelist:
removed DocumentInfo
where possible using PathBuf instead of uri
refactoring
=> No doc info copy

src/caps.rs, src/known_models.rs
works with https://github.com/smallcloudai/refact/pull/407
=> models_dict_patch handling

src/at_commands/at_ast_definition.rs, src/at_commands/at_ast_file_symbols.rs, src/at_commands/at_ast_lookup_symbols.rs, src/at_commands/at_ast_reference.rs, src/at_commands/at_commands.rs, src/at_commands/at_workspace.rs, src/http/routers/v1/at_commands.rs
Changelist:
* if vecdb or ast are turned off, some at-commands will be hidden from at-completion
=> hide unavailable at commands

src/ast/treesitter/parsers/java.rs, src/ast/treesitter/parsers/tests/cases/java/main.java.json
fixed function call symbol with incorrect lang
fixed tests for java parser
=> fixed java parser stack overflow for big files

src/at_commands/execute.rs
Improve word parsing by refining regex and trimming punctuation
=> Win paths fix

src/caps.rs, src/forward_to_openai_endpoint.rs, src/http/routers/v1/chat.rs, src/scratchpads/chat_passthrough.rs, src/scratchpads/mod.rs
Known problems: DEFAULT_SYSTEM_PROMPT is the same for models with tools and without. Probably we need mechanism for switching it.
=> do not pass tools if model does not support it

src/at_tools/tools.rs, src/http/routers/v1/at_tools.rs, src/vecdb/handler.rs, src/vecdb/vectorizer_service.rs
Changelist:
* uodate_indexed_file_paths removed (not needed)
* tools that have deps (vecdb or ast) will be hidden if deps not enabled
=> Few fixes from diffs -- cherry-pick

src/toolbox/toolbox_compiled_in.rs, src/toolbox/toolbox_config.rs
```
ENVIRONMENT INFO:
DATETIME: 2024-08-19 19:15:10
OS: macos
USER: valaises
WORKSPACE_DIRS:
/Users/valaises/RustroverProjects/refact-lsp
```
=> environment info in system prompt

src/at_commands/at_file.rs, src/at_commands/at_tree.rs, src/at_tools/att_cat.rs, src/at_tools/att_diff.rs, src/at_tools/att_search.rs, src/at_tools/att_tree.rs, src/diffs.rs, src/files_correction.rs, src/http/routers/v1/at_commands.rs, src/scratchpads/pp_context_files.rs, src/scratchpads/pp_utils.rs
=> pretty filenames for at_preview && let user operate on shorter paths

src/scratchpads/chat_generic.rs, src/scratchpads/chat_llama2.rs, src/scratchpads/chat_passthrough.rs, src/toolbox/toolbox_compiled_in.rs, src/toolbox/toolbox_config.rs
if custom system prompt contains a variable %WORKSPACE_PROJECTS_INFO% -> postprocess it.
=> Custom prompt insert info

Cargo.toml, src/tools/tool_relevant_files.rs
* Preserve sorting for serde_json
* Sorting of localize output
* Skeletonization and 80 usefulness max for files (100 for symbol however)
=> Locate sort

src/files_correction.rs, src/files_in_workspace.rs, src/tools/tool_cat.rs, src/tools/tool_tree.rs
if path provided, tree will use FS
=> path completion uses FS + cat, tree improvements

src/diffs.rs, src/files_in_workspace.rs, src/http/routers/v1/patch.rs, tests/test11_patch_partial_edit.py
=> Patch refactoring 2

src/tools/tool_patch_aux/tickets_parsing.rs, tests/test11_data/toad_add_to_file_01.py, tests/test11_data/toad_add_to_file_02.py, tests/test11_data/toad_add_to_file_03.py, tests/test11_data/toad_add_to_file_04.py, tests/test11_data/toad_add_to_file_05.py, tests/test11_data/toad_rewrite_symbol_01.py, tests/test11_data/toad_rewrite_symbol_02.py, tests/test11_data/toad_rewrite_symbol_03.py, tests/test11_patch.py
=> Trim trailing whitespace in the patch

src/ast/ast_indexer_thread.rs, src/file_filter.rs, src/files_in_workspace.rs, src/vecdb/vdb_thread.rs
* file is indexed even if it has no extension or extension is not in the list
* extension is checked only when file gets queued for AST or VecDB
=> All files under VCS are indexed

src/vecdb/vdb_structs.rs, src/vecdb/vdb_thread.rs
https://refact.fibery.io/Software_Development/Plan-Week-of-Oct-21---by-dev-165#Task/Stats-how-many-requests-were-400-204
=> vecdb status errors information (via rag-status & in logs)

src/files_correction.rs
Extra autocorrection of the path for a common model's mistake
=> Windows paths fixes

src/integrations/integr_chrome.rs
* eval: evaluate js expression on given tab
* styles: css for given element (too large ouutput, probably we need to truncate it in some way)
* click: point or element
=> Chrome new commands

src/integrations/integr_chrome.rs
* filtering for style command
* scroll_to command added
* html for given element limited by 3000 symbols
* mobile device window size
* eval output
=> Chrome improvements 09 12 24

src/integrations/integr_chrome.rs
* wait_for meta command, sleeps for 1-5 seconds on tab, usable for making shots and collecting logs
* press_key command rename and extend, can now use any key and can modify it with ctrl, alt, shift and meta
=> Chrome improvements 16.12.24

src/known_models.rs
https://refact.fibery.io/Software_Development/New-document-428
=> Gemini Support

src/at_commands/at_tree.rs, src/integrations/project_summary_chat.rs, src/yaml_configs/customization_compiled_in.yaml
https://refact.fibery.io/Software_Development/Current-Week-by-state-358#Task/Improve-project-summarization-584
=> Project Summary Improvements

src/file_filter.rs
add .liquid file extension for shopify template lang support
ignore .gradle build dir
=> Lang_support

src/tools/tool_patch_aux/tickets_parsing.rs
=> Improving backticks parsing in the patch

src/known_models.rs
should be released with new docker
=> vllm serve

docker/lsp-debug.Dockerfile, python_binding_and_cmdline/refact/chat_client.py, src/http/routers/v1/chat.rs, src/scratchpads/chat_passthrough.rs, src/scratchpads/chat_utils_prompts.rs, src/tools/tools_execute.rs
This pull request includes changes aimed at improving code efficiency and readability, as well as fixing this minor issue:
[`python_binding_and_cmdline/refact/chat_client.py`](diffhunk://#diff-a382ec549d15ddd0e1a318fe6a8b7e913ff003541ac707d337060b9f7a71e8e9L310-R310): Fixed the assignment of `end_str` to use `line_str` instead of buffer, since buffer is empty at this point, previously it wasn't throwing an exception when it should.
=> Assorted optimizations and fixes

Cargo.toml, src/integrations/integr_cmdline.rs, src/tools/tool_cat.rs
- use shell escape for cmd tool
- remove duplicate filenames in cat tool (ui)
=> some fixes for cmd tool and cat tool
